### ISSUE TITLE
"Address already in use" with t_rex container on GKE

### ISSUE THREAD

**Issue by musicformellons** [t-rex-tileserver/t-rex#117]
I had a nice working T-rex server on a cloud ubuntu server, but now would like have it running in Kubernetes (GKE) with istio. My dockerfile is:
```
FROM ubuntu:xenial

RUN echo "deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial main" >> /etc/apt/sources.list
RUN gpg --keyserver keyserver.ubuntu.com --recv 314DF160
RUN gpg --export --armor 314DF160 | apt-key add -

RUN apt-get update && apt-get install -y openssl libgdal20 gdal-bin nano

ADD t-rex-*.deb .
RUN dpkg -i t-rex-*.deb
RUN rm t-rex-*.deb

WORKDIR /home/usr

#VOLUME ["/var/data/in"]
VOLUME ["/home/usr"]
#VOLUME ["/var/data/out"]
VOLUME ["/home/usr/mvtcache"]

EXPOSE 1337
ENV RUST_BACKTRACE 1
COPY osm.toml /home/usr/
ENTRYPOINT ["/usr/bin/t_rex"]
CMD ["serve", "-c", "/home/usr/osm.toml"]
```
My osm.toml config file:
```
[service.mvt]
viewer = true

[[datasource]]
name = "postgres"
dbconn = "postgresql://postgres:mypassword@localhost:5432/postgres"

[grid]
predefined = "web_mercator"

[[tileset]]
name = "points"

[[tileset.layer]]
name = "points"
table_name = "points"
geometry_field = "wkb_geometry"
geometry_type = "POINT"
srid = 4326
simplify = true

[[tileset.layer.query]]
sql = """SELECT wkb_geometry,"id","url","front_image","city","created_at"::TEXT,"updated_at"::TEXT FROM points WHERE wkb_geometry && !bbox!"""

  [[tileset.layer.query]]
  minzoom = 0
  maxzoom = 21

[cache.file]
base = "/home/usr/mvtcache"

[webserver]
bind = "localhost"
port = 1337
threads = 20
```
The relevant manifest part:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: t-rex-server
          image: gcr.io/myproject/t_rex:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          env:
            - name: POSTGRES_DB_HOST
              value: 127.0.0.1:5432
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          livenessProbe:
            exec:
              command:
                - cat
                - /conf/osm.toml
            initialDelaySeconds: 10
            periodSeconds: 5
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=myproject:europe-west4:osm=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
```

I get following error on the t-rex-server container:
```
~$ kubectl logs myapp-c66bc587-v6pm4 t-rex-server 
2019-01-23 22:46:50.554 INFO Reading configuration from '/home/usr/osm.toml'
2019-01-23 22:47:20.554 INFO Couldn't connect with TlsMode::None - retrying with TlsMode::Require
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitializationError(None)', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main
  14: <unknown>

```
