### ISSUE TITLE
data(srid = 4326) does not display in viewer

### ISSUE THREAD

**Issue by luqinghui** [t-rex-tileserver/t-rex#176]
### Step1 
I download some data from [GADM](https://gadm.org/download_country_v3.html), and i import it to postgis using shp2pgsql.
``` sh
shp2pgsql -s 4326 -I ~/Downloads/gadm36_AFG_shp/gadm36_AFG_0.shp public.afg | psql -d gadm -U postgiser -W -h 0.0.0.0
```
So now I have a layer(afg).

### Step2
I transfrom the data to 3857 using the `st_transfrom(geom, 3857)`. 
``` sql
   select *  into public.afg_3857  
    from (select st_setsrid(st_transform(geom, 3857), 3857) as geom  
               from public.afg a) as foo;
```
So now, I have two layers(afg and afg_3857).

### Step3
I generate some point in afg polygon using the `st_generatepoints(geom, 2000)`.
``` sql
   select (st_dump(t.geom)).geom  
      into public.afg_point_4326  
     from (select st_generatepoints(geom, 2000) as geom  
                from public.afg a) as t;
```
So now I have three layers(afg, afg_3857 and afg_point_4326).

### Step4
I generate the config file using `t_rex genconfig`. Then I change afg_3857 srid to 3857 and afg_point_4326 to 4326(the original is 0, they cannot be auto recongized correctly).
``` toml
# t-rex configuration

[service.mvt]
viewer = true

[[datasource]]
dbconn = "postgresql://postgiser:postgiser123456@localhost/gadm"
name = "dbconn"
default = true

[grid]
# Predefined grids: web_mercator, wgs84
predefined = "web_mercator"

[[tileset]]
name = "afg"
extent = [60.50487, 29.36157, 74.89413, 38.49092]
[[tileset.layer]]
name = "afg"
table_name = "afg"
geometry_field = "geom"
geometry_type = "MULTIPOLYGON"
srid = 4326
#fid_field = "id"
#tile_size = "4096"
buffer_size = 1
simplify = true
query_limit = 1000
#[[tileset.layer.query]]
#sql = """SELECT ST_Transform(geom,3857) AS geom,"gid","gid_0","name_0" FROM afg WHERE geom && !bbox!"""

[[tileset]]
name = "afg_3857"
#extent = [-180.0,-90.0,180.0,90.0]
[[tileset.layer]]
name = "afg_3857"
table_name = "afg_3857"
geometry_field = "geom"
geometry_type = "MULTIPOLYGON"
srid = 3857
#fid_field = "id"
#tile_size = "4096"
buffer_size = 1
simplify = true
query_limit = 1000
#[[tileset.layer.query]]
#sql = """SELECT ST_SetSRID(geom,3857) AS geom FROM afg_3857 WHERE geom && !bbox!"""

[[tileset]]
name = "afg_point_4326"
#extent = [-180.0,-90.0,180.0,90.0]
[[tileset.layer]]
name = "afg_point_4326"
table_name = "afg_point_4326"
geometry_field = "geom"
geometry_type = "POINT"
srid = 4326
#fid_field = "id"
#tile_size = "4096"
buffer_size = 0
query_limit = 1000
#[[tileset.layer.query]]
#sql = """SELECT ST_SetSRID(geom,3857) AS geom FROM afg_point_4326 WHERE geom && !bbox!"""

#[cache.file]
#base = "/tmp/mvtcache"
#baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "0.0.0.0"
port = 6767
threads = 4
#cache_control_max_age = 43200
```
### Step5
When I start the server, the afg_3857 and afg_point_4326 can be displayed by viewer, but the original data afg can not.
![图片](https://user-images.githubusercontent.com/5338140/69395900-85e6e080-0d1b-11ea-91a9-333dc36f5c82.png)
![图片](https://user-images.githubusercontent.com/5338140/69395670-cc880b00-0d1a-11ea-81dd-4136857702da.png)
![图片](https://user-images.githubusercontent.com/5338140/69395673-d27dec00-0d1a-11ea-86e9-944cce9aad4c.png)

Why the same srid(4326), one can display but another can not?
I am confused if my config file is wrong or it is a bug or feature?
My system is Debian 9 and t_rex version is v0.8.2(i tried v0.10.0, the result was same as v0.8.2).
