### ISSUE TITLE
Unable to serve correct tiles

### ISSUE THREAD

**Issue by yarray** [t-rex-tileserver/t-rex#282]
I tried multiple sources including Natural Earth, UIA, etc., with both shapefile and postgis as datasources. However, although I could see some lines/polygons sometimes, it seemed that the tiles were always incorrect. To illustrate the problem, I created two datasets of polygons.

The first one contained several large polygons, like:

<img width="1297" alt="截屏2022-02-16 下午1 14 50" src="https://user-images.githubusercontent.com/1227829/154201499-3fb2db73-74c6-407f-8b67-b99170ead4e6.png">

I then generated config with

`./t_rex genconfig --datasource <path>/large_polygon.shp > config.test.toml`

and then served the tileset with

`RUST_LOG=debug ./t_rex serve -c config.dresden.toml`

In the Xray tab:

<img width="1790" alt="截屏2022-02-16 下午1 28 10" src="https://user-images.githubusercontent.com/1227829/154202086-1d7fb7c3-50f3-443c-8014-e7014e60b3ad.png">

The log printed "1 features" for some tiles. It also occasionally printed "ERROR 1: latitude or longitude exceeded limits". I'm not sure whether it's related to the final output. 

<img width="1792" alt="截屏2022-02-16 下午2 39 10" src="https://user-images.githubusercontent.com/1227829/154210043-cea1a3fd-71d3-4a60-9957-b69ecb20c249.png">

The corresponding config was:

```toml
# t-rex configuration

[service.mvt]
viewer = true

[[datasource]]
path = "/Users/yarray/data/test/large_polygon.shp"
name = "datasource"
default = true

[grid]
predefined = "web_mercator"

[[tileset]]
name = "large_polygon"
extent = [65.11901, 15.94669, 129.20218, 60.21640]
[[tileset.layer]]
name = "large_polygon"
table_name = "large_polygon"
geometry_field = ""
geometry_type = "POLYGON"
srid = 4326
buffer_size = 1
#make_valid = true
simplify = true
query_limit = 1000
#[[tileset.layer.query]]

#[cache.file]
#base = "/tmp/mvtcache"
#baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "127.0.0.1"
port = 6767

#[[webserver.static]]
#path = "/static"
#dir = "./public/"
```

The input shapefile was [large_polygon.zip](https://github.com/t-rex-tileserver/t-rex/files/8077369/large_polygon.zip).
