### ISSUE TITLE
SSL connection to postgresql does not work (panic)

### ISSUE THREAD

**Issue by RemiDesgrange** [t-rex-tileserver/t-rex#80]
Hi,

Try to get it working with docker and a distant postgresql server accessible only via SSL connexion. 

When I try to get the version:

```
docker run -p 6767:6767 -v $PWD:/conf sourcepole/t-rex serve -V
t_rex-serve

```
? is it a bug ?

The toml file is:
```toml
[service.mvt]
viewer = true

[[datasource]]
name = "mydb"

dbconn = "postgresql://<user>:<pass>@mydb.host.example.com:5432/mydb?sslmode=require"

[grid]
predefined = "web_mercator"

[[tileset]]
name = "network"

[[tileset.layer]]
name = "points"
datasource = "mydb"
# Select all attributes of table:
table_name = "projet.v_ljsdflkj"
geometry_field = "the_geom"
geometry_type = "POINT"
fid_field = "ljsdflkj_id"


[[tileset.layer]]
name = "linestring"
datasource = "mydb"
# Select all attributes of table:
table_name = "projet.v_kjdfg"
geometry_field = "the_geom"
geometry_type = "LINESTRING"
fid_field = "kjdfg_id"



[webserver]
bind = "0.0.0.0"
port = 6767
threads = 4
```
